name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macOS-latest]
        exclude:  # Python 3.7 is not supported on Apple ARM64
          - python-version: "3.7"
            os: macos-latest
        include: # Python 3.7 is tested with a x86 macOS version
          - python-version: "3.7"
            os: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: requirements/*.pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test.pip
    - name: Test with pytest
      run: |
        python3 -m pytest
    - name: Lint with flake8
      run: |
        flake8 .
